print("\033[1;32;40m")
#print("╔"+"═"*20+"╗")
print("╔═════════════════════╗")
print("║\033[1;31;40m   HESAP MAKİNESİ  \033[1;32;40m  ║")
print("║                     ║")
print("║  1-FIFA             ║")
print("║  2-Battlefield      ║")
print("║  3-CS2              ║")
print("║  4-GTA V            ║")
print("║                     ║")
print("║    Seçimiz nedir?   ║")
print("╚═════════════════════╝")
secim = input()
if secim=="1":print ("FIFA'yı seçtin")
if secim=="2":print ("Battlefield'ı seçtin")
if secim=="3":print ("CS2'yi seçtin")